sonar.projectKey=fuchi-no-dokuneko_UsefulTool
sonar.organization=fuchi-no-dokuneko
sonar.host.url=https://sonarcloud.io
sonar.projectName=UsefulTool
sonar.sourceEncoding=UTF-8
sonar.sources=toolkit.js,assets/pages
sonar.exclusions=assets/pages/video-studio/vendor/**
sonar.tests=tests,acceptance/features
sonar.test.inclusions=tests/**,acceptance/features/**
sonar.javascript.lcov.reportPaths=build/reports/browser-uat/lcov.info
sonar.testExecutionReportPaths=build/reports/browser-uat/sonar-test-execution.xml
