import { promises as fs } from "node:fs";
import crypto from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputDirectory = path.join(root, "offline");
const pages = (await fs.readdir(root)).filter((name) => name.endsWith(".html")).sort();

function isLocal(reference) {
  return !/^(?:[a-z]+:|\/\/|#)/i.test(reference);
}

function localFileReference(reference) {
  return reference.replace(/[?#].*$/, "");
}

function safeScript(source) {
  return source.replace(/<\/script/gi, "<\\/script");
}

function allowCspSource(html, directive, source) {
  const pattern = new RegExp(`${directive}[^;\"]*`);
  return html.replace(pattern, (value) => value.split(/\s+/).includes(source) ? value : `${value} ${source}`);
}

async function inlineModuleImports(source, scriptPath) {
  let output = source;
  const imports = [...source.matchAll(/from\s+(["'])(\.\.?\/[^"']+\.m?js)\1/g)];
  for (const match of imports) {
    const modulePath = path.resolve(path.dirname(scriptPath), match[2]);
    const moduleSource = await fs.readFile(modulePath, "utf8");
    const dataUrl = "data:text/javascript;base64," + Buffer.from(moduleSource).toString("base64");
    output = output.replace(match[0], `from ${match[1]}${dataUrl}${match[1]}`);
  }
  return output;
}

async function inlinePage(name) {
  if (name === "video-editor.html") {
    const { execFileSync } = await import("node:child_process");
    execFileSync(process.execPath, [path.join(root, "scripts/build-video-studio.mjs")]);
    return fs.readFile(path.join(outputDirectory, name), "utf8");
  }
  const sourcePath = path.join(root, name);
  let html = await fs.readFile(sourcePath, "utf8");

  const workerBlocks = [...html.matchAll(/<script([^>]*)\s+data-inline-worker-src="([^"]+)"([^>]*)><\/script>/g)];
  for (const match of workerBlocks) {
    if (!isLocal(match[2])) continue;
    const workerPath = path.resolve(root, path.dirname(name), localFileReference(match[2]));
    const workerSource = safeScript(await fs.readFile(workerPath, "utf8"));
    const attributes = (match[1] + match[3]).trim();
    html = html.replace(match[0], () => `<script${attributes ? " " + attributes : ""} data-inlined-from="${match[2]}">\n${workerSource}\n</script>`);
  }

  const styles = [...html.matchAll(/<link\s+rel="stylesheet"\s+href="([^"]+)"\s*>/g)];
  for (const match of styles) {
    if (!isLocal(match[1])) continue;
    const css = (await fs.readFile(path.resolve(root, path.dirname(name), localFileReference(match[1])), "utf8"))
      .replace(/<\/style/gi, "<\\/style");
    html = html.replace(match[0], () => `<style data-inlined-from="${match[1]}">\n${css}\n</style>`);
    html = allowCspSource(html, "style-src", "'unsafe-inline'");
  }

  const scripts = [...html.matchAll(/<script([^>]*)\s+src="([^"]+)"([^>]*)><\/script>/g)];
  for (const match of scripts) {
    if (!isLocal(match[2])) continue;
    const scriptPath = path.resolve(root, path.dirname(name), localFileReference(match[2]));
    const javascript = safeScript(await inlineModuleImports(await fs.readFile(scriptPath, "utf8"), scriptPath));
    const attributes = (match[1] + match[3]).trim();
    html = html.replace(match[0], () => `<script${attributes ? " " + attributes : ""} data-inlined-from="${match[2]}">\n${javascript}\n</script>`);
    html = allowCspSource(html, "script-src", "'unsafe-inline'");
    if (javascript.includes("data:text/javascript;base64,")) {
      html = allowCspSource(html, "script-src", "data:");
    }
  }

  html = html.replace(/href="offline\/([^"]+\.html)"/g, 'href="$1"');
  html = html.replace("<!doctype html>", "<!doctype html>\n<!-- Generated by scripts/build-offline.mjs. Do not edit directly. -->");
  return html;
}

await fs.mkdir(outputDirectory, { recursive: true });
const manifest = { schema: "usefultool-offline.v1", pages: [] };
for (const name of pages) {
  const artifact = await inlinePage(name);
  await fs.writeFile(path.join(outputDirectory, name), artifact);
  manifest.pages.push({
    file: name,
    bytes: Buffer.byteLength(artifact),
    sha256: crypto.createHash("sha256").update(artifact).digest("hex"),
  });
}
await fs.writeFile(path.join(outputDirectory, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`Generated ${pages.length} self-contained pages in offline/.`);
