import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputDirectory = path.join(root, "offline");
const pages = (await fs.readdir(root)).filter((name) => name.endsWith(".html")).sort();

function isLocal(reference) {
  return !/^(?:[a-z]+:|\/\/|#)/i.test(reference);
}

function safeScript(source) {
  return source.replace(/<\/script/gi, "<\\/script");
}

async function inlinePage(name) {
  const sourcePath = path.join(root, name);
  let html = await fs.readFile(sourcePath, "utf8");

  const styles = [...html.matchAll(/<link\s+rel="stylesheet"\s+href="([^"]+)"\s*>/g)];
  for (const match of styles) {
    if (!isLocal(match[1])) continue;
    const css = (await fs.readFile(path.resolve(root, path.dirname(name), match[1]), "utf8"))
      .replace(/<\/style/gi, "<\\/style");
    html = html.replace(match[0], () => `<style data-inlined-from="${match[1]}">\n${css}\n</style>`);
  }

  const scripts = [...html.matchAll(/<script([^>]*)\s+src="([^"]+)"([^>]*)><\/script>/g)];
  for (const match of scripts) {
    if (!isLocal(match[2])) continue;
    const javascript = safeScript(await fs.readFile(path.resolve(root, path.dirname(name), match[2]), "utf8"));
    const attributes = (match[1] + match[3]).trim();
    html = html.replace(match[0], () => `<script${attributes ? " " + attributes : ""} data-inlined-from="${match[2]}">\n${javascript}\n</script>`);
  }

  const imports = [...html.matchAll(/from\s+(["'])(\.\.?\/[^"']+\.m?js)\1/g)];
  for (const match of imports) {
    const moduleSource = await fs.readFile(path.resolve(root, path.dirname(name), match[2]), "utf8");
    const dataUrl = "data:text/javascript;base64," + Buffer.from(moduleSource).toString("base64");
    html = html.replace(match[0], `from ${match[1]}${dataUrl}${match[1]}`);
    html = html.replace("script-src 'self' 'unsafe-inline'", "script-src 'self' 'unsafe-inline' data:");
  }

  html = html.replace(/href="offline\/([^"]+\.html)"/g, 'href="$1"');
  html = html.replace("<!doctype html>", "<!doctype html>\n<!-- Generated by scripts/build-offline.mjs. Do not edit directly. -->");
  return html;
}

await fs.mkdir(outputDirectory, { recursive: true });
for (const name of pages) await fs.writeFile(path.join(outputDirectory, name), await inlinePage(name));
console.log(`Generated ${pages.length} self-contained pages in offline/.`);
